protect_pets_from: [PlayerDamage, OwnerDamage, EnvironmentalDamage, MobDamage]
tp_pets_between_worlds: true
allow_untaming_pets: true
total_pet_limit: -1
dog_limit: -1
cat_limit: -1
bird_limit: -1
horse_limit: -1
mule_limit: -1
llama_limit: -1
donkey_limit: -1
storage_limit: 5
tools:
  untame_pets: [SHEARS]
  get_owner: [BONE]
command_aliases:
  protected: [prot, p, pr]
  lost: [lostandfound, laf, lf, l]
  tp: [teleport, find]
  rename: [setname]
  allow: [add]
  remove: [take]
  allowed: [permitted]
  list: [show]
  all: [pets]
  store: [move, stable]
  storage: [setstable]
  help: [pls]
mysql:
  enable: false
  host: localhost
  port: 3306
  database: minecraft
  username: 'mcpluginuser'
  password: 'password'
logging:
  updated_pets: true
  successful_actions: true
  unsuccessful_actions: true
  prevented_damage: true
  errors: true
schema_version: 3